/**
 * zipExporter.ts - Generates framework-specific project template ZIP archives.
 */

import JSZip from 'jszip';
import { WorkflowExportContext } from './workflowCodeExporter';

export interface ZipProjectTemplate {
  files: Record<string, string>;
  rootFolder: string;
}

function sanitize(name: string): string {
  return (
    (name || 'my_agent')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '') || 'my_agent'
  );
}

// ─── 1. Raw LLM API + Python ─────────────────────────────────────────────────
// Structure from: OpenAI Python quickstart docs
// my_openai_project/
// ├── .env
// ├── .gitignore
// ├── requirements.txt
// ├── README.md
// └── src/
//     └── main.py
export function buildRawLLMZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);
  return {
    rootFolder: name,
    files: {
      'src/main.py': code,
      'requirements.txt': 'openai\npython-dotenv\n',
      '.env': 'OPENAI_API_KEY=sk-your-actual-api-key-here\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'README.md': [
        `# ${ctx.title || 'My Agent'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **Raw LLM API + Python**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv',
        'source .venv/bin/activate   # Windows: .venv\\Scripts\\activate',
        'pip install -r requirements.txt',
        '# Add your OPENAI_API_KEY to .env',
        'python src/main.py',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 2. Google ADK ───────────────────────────────────────────────────────────
// Structure from: Google ADK official docs
// my_agent/
//     agent.py      # main agent code
//     .env          # API keys or project IDs
//     __init__.py
export function buildGoogleADKZip(_ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  return {
    rootFolder: 'my_agent',
    files: {
      'agent.py': code,
      '.env': 'GEMINI_API_KEY=your_gemini_api_key_here\n',
      '__init__.py':
        'from .agent import WorkflowOrchestrator\n\n__all__ = ["WorkflowOrchestrator"]\n',
    },
  };
}

// ─── 3. LangChain ────────────────────────────────────────────────────────────
// Structure from: LangChain / LangSmith deployment docs
// my-langchain-app/
// ├── src/
// │   ├── chains/
// │   ├── tools/
// │   ├── prompts/
// │   └── utils/
// ├── .env
// ├── .gitignore
// ├── pyproject.toml
// └── requirements.txt
export function buildLangChainZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);
  return {
    rootFolder: name,
    files: {
      'src/chains/workflow.py': code,
      'src/chains/__init__.py':
        'from .workflow import run_langchain_workflow\n\n__all__ = ["run_langchain_workflow"]\n',
      'src/tools/__init__.py': '# Place your custom @tool definitions here\n',
      'src/prompts/__init__.py': '# Place your reusable ChatPromptTemplate definitions here\n',
      'src/utils/__init__.py': '# Helper utilities\n',
      'src/main.py': `"""Entry point"""\nfrom src.chains.workflow import run_langchain_workflow\n\nif __name__ == "__main__":\n    result = run_langchain_workflow()\n    import json\n    print(json.dumps(result, indent=2))\n`,
      '.env':
        'OPENAI_API_KEY=sk-your-openai-api-key-here\nLANGSMITH_API_KEY=\nLANGSMITH_TRACING=false\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'pyproject.toml': `[project]\nname = "${name}"\nversion = "0.1.0"\nrequires-python = ">=3.10"\ndependencies = [\n    "langchain>=0.3.0",\n    "langchain-core",\n    "langchain-openai",\n    "python-dotenv",\n    "pydantic>=2.0.0"\n]\n\n[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n`,
      'requirements.txt':
        'langchain>=0.3.0\nlangchain-core\nlangchain-openai\npython-dotenv\npydantic>=2.0.0\n',
      'README.md': [
        `# ${ctx.title || 'My LangChain App'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **LangChain**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv && source .venv/bin/activate',
        'pip install -r requirements.txt',
        '# Add your OPENAI_API_KEY to .env',
        'python src/main.py',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 4. LangGraph ────────────────────────────────────────────────────────────
// Structure from: LangGraph CLI / LangSmith deployment docs
// my-app/
// ├── my_agent/
// │   ├── utils/
// │   │   ├── tools.py
// │   │   ├── nodes.py
// │   │   └── state.py
// │   ├── __init__.py
// │   └── agent.py
// ├── .env
// ├── requirements.txt
// └── langgraph.json
export function buildLangGraphZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);
  return {
    rootFolder: name,
    files: {
      'my_agent/agent.py': code,
      'my_agent/__init__.py':
        'from .agent import create_workflow_graph\n\n__all__ = ["create_workflow_graph"]\n',
      'my_agent/utils/__init__.py': '',
      'my_agent/utils/state.py':
        '"""State definitions for the workflow graph."""\nfrom typing import TypedDict, Any\n\nclass WorkflowState(TypedDict, total=False):\n    messages: list\n    data: dict\n',
      'my_agent/utils/nodes.py':
        '"""Node logic functions for the workflow graph."""\n# Import and use node functions defined in agent.py\n',
      'my_agent/utils/tools.py':
        '"""Tool definitions for graph nodes."""\nfrom langchain_core.tools import tool\n\n# Define your custom @tool functions here\n',
      '.env': 'OPENAI_API_KEY=sk-your-openai-api-key-here\nLANGSMITH_API_KEY=\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'langgraph.json':
        JSON.stringify(
          {
            dependencies: ['.'],
            graphs: { workflow: './my_agent/agent.py:create_workflow_graph' },
            env: '.env',
          },
          null,
          2,
        ) + '\n',
      'requirements.txt':
        'langgraph>=0.1.0\nlangchain-openai>=0.1.0\nlangchain-core>=0.2.0\npython-dotenv>=1.0.0\n',
      'README.md': [
        `# ${ctx.title || 'My LangGraph App'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **LangGraph**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'pip install -U "langgraph-cli[inmem]"',
        'pip install -r requirements.txt',
        '# Add your OPENAI_API_KEY to .env',
        'python my_agent/agent.py',
        '```',
        '',
        '## Deploy with LangGraph CLI',
        '',
        '```bash',
        'langgraph dev',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 5. OpenAI Agents SDK ────────────────────────────────────────────────────
// Structure from: OpenAI Agents SDK GitHub / openai.github.io/openai-agents-python
// my_agent_project/
// ├── main.py
// ├── agents/
// │   ├── __init__.py
// │   └── workflow_agent.py
// ├── tools/
// │   └── __init__.py
// ├── guardrails/
// │   └── __init__.py
// ├── .env
// └── requirements.txt
export function buildOpenAIAgentsZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);
  return {
    rootFolder: name,
    files: {
      'main.py': code,
      'agents/__init__.py': '# Import your agent definitions here\n',
      'agents/workflow_agent.py':
        '"""Specialist agent definitions."""\n# from agents import Agent\n# Define sub-agents here and import in main.py\n',
      'tools/__init__.py': '# Custom function tools definitions\n',
      'guardrails/__init__.py': '# Input/output validation logic\n',
      '.env': 'OPENAI_API_KEY=sk-your-openai-api-key-here\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'requirements.txt': 'openai-agents\npython-dotenv\n',
      'README.md': [
        `# ${ctx.title || 'My OpenAI Agent'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **OpenAI Agents SDK**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv && source .venv/bin/activate',
        'pip install -r requirements.txt',
        '# Add your OPENAI_API_KEY to .env',
        'python main.py',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 6. CrewAI ───────────────────────────────────────────────────────────────
// Structure from: `crewai create crew <project>` official CLI (JSON-first default)
// my_project/
// ├── .gitignore
// ├── .env
// ├── agents/
// │   └── researcher.jsonc
// ├── crew.jsonc
// ├── knowledge/
// ├── pyproject.toml
// ├── README.md
// ├── skills/
// └── tools/
export function buildCrewAIZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);

  const crewJsonc = JSON.stringify(
    {
      name: ctx.title || 'My Crew',
      description: 'AutoAgent generated CrewAI crew',
      process: 'sequential',
      agents: ['agents/researcher.jsonc'],
      verbose: true,
      memory: true,
    },
    null,
    2,
  );

  const agentJsonc = JSON.stringify(
    {
      role: 'Research Specialist',
      goal: 'Execute workflow tasks with precision',
      backstory: 'An expert AI agent specializing in structured task execution.',
      llm: 'gpt-4o-mini',
      tools: [],
      verbose: true,
      memory: true,
    },
    null,
    2,
  );

  return {
    rootFolder: name,
    files: {
      // The generated Python crew code as the main logic reference
      'src/crew.py': code,
      'crew.jsonc': crewJsonc,
      'agents/researcher.jsonc': agentJsonc,
      'knowledge/.gitkeep': '',
      'skills/.gitkeep': '',
      'tools/__init__.py': '# Place your custom CrewAI tools here\n',
      'pyproject.toml': `[project]\nname = "${name}"\nversion = "0.1.0"\nrequires-python = ">=3.10"\ndependencies = [\n    "crewai>=0.36.0",\n    "crewai-tools>=0.4.0"\n]\n\n[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n`,
      '.env': 'OPENAI_API_KEY=sk-your-openai-api-key-here\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'README.md': [
        `# ${ctx.title || 'My CrewAI Crew'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **CrewAI**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'pip install crewai crewai-tools',
        '# Add your OPENAI_API_KEY to .env',
        'crewai run',
        '```',
        '',
        '## Alternative: Run with Python',
        '',
        '```bash',
        'pip install -r requirements.txt 2>/dev/null || pip install crewai crewai-tools python-dotenv',
        'python src/crew.py',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 7. AutoGen ──────────────────────────────────────────────────────────────
// Structure from: Microsoft AutoGen official docs (v0.4+)
// my-autogen-project/
// ├── .env
// ├── main.py
// ├── agents/
// │   ├── __init__.py
// │   └── researcher.py
// ├── tools/
// │   ├── __init__.py
// │   └── search_tool.py
// ├── config/
// │   └── oai_config.json
// └── requirements.txt
export function buildAutoGenZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);

  const oaiConfig = JSON.stringify(
    [
      {
        model: 'gpt-4o-mini',
        api_type: 'openai',
      },
    ],
    null,
    2,
  );

  return {
    rootFolder: name,
    files: {
      'main.py': code,
      'agents/__init__.py': '# Agent persona definitions\n',
      'agents/researcher.py':
        '"""Example agent definition."""\n# from autogen_agentchat.agents import AssistantAgent\n# Define specialist agents here\n',
      'tools/__init__.py': '# Custom function tool definitions\n',
      'tools/search_tool.py':
        '"""Example tool definition."""\n# Define tools as plain Python async functions\n',
      'config/oai_config.json': oaiConfig,
      '.env': 'OPENAI_API_KEY=sk-your-openai-api-key-here\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'requirements.txt': 'autogen-agentchat\nautogen-ext[openai]\npython-dotenv\n',
      'README.md': [
        `# ${ctx.title || 'My AutoGen Project'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **AutoGen (Microsoft)**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv && source .venv/bin/activate',
        'pip install -r requirements.txt',
        '# Add your OPENAI_API_KEY to .env',
        'python main.py',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 8. LlamaIndex ───────────────────────────────────────────────────────────
// Structure from: LlamaIndex Workflows official docs
// my_llamaindex_project/
// ├── main.py           # Entry point
// ├── workflow.py       # Workflow class with @step methods
// ├── events.py         # Custom Event class definitions
// ├── data/             # Local documents / knowledge base
// ├── .env
// └── requirements.txt
export function buildLlamaIndexZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);
  return {
    rootFolder: name,
    files: {
      'workflow.py': code,
      'events.py':
        [
          '"""Custom Event definitions for the LlamaIndex Workflow."""',
          'from typing import Any, Dict',
          'from llama_index.core.workflow import Event',
          '',
          '# Define your custom event payloads here',
          'class InputEvent(Event):',
          '    payload: Dict[str, Any]',
          '',
          'class OutputEvent(Event):',
          '    result: Any',
        ].join('\n') + '\n',
      'main.py':
        [
          '"""Entry point – runs the LlamaIndex Workflow."""',
          'import asyncio',
          'from workflow import create_workflow',
          '',
          'async def main():',
          `    wf = create_workflow()`,
          `    result = await wf.run(input="${ctx.prompt || 'Execute automation'}")`,
          '    print("\\n=== Workflow Complete ===")',
          '    print(result)',
          '',
          'if __name__ == "__main__":',
          '    asyncio.run(main())',
        ].join('\n') + '\n',
      'data/.gitkeep': '',
      '.env': 'OPENAI_API_KEY=sk-your-openai-api-key-here\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'requirements.txt':
        'llama-index-core\nllama-index-workflows\nllama-index-llms-openai\npython-dotenv\n',
      'README.md': [
        `# ${ctx.title || 'My LlamaIndex Workflow'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **LlamaIndex**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv && source .venv/bin/activate',
        'pip install -r requirements.txt',
        '# Add your OPENAI_API_KEY to .env',
        'python main.py',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 9. Semantic Kernel ──────────────────────────────────────────────────────
// Structure from: Microsoft Semantic Kernel Python docs
// my_sk_project/
// ├── main.py
// ├── plugins/
// │   └── WorkflowPlugin/
// │       ├── skprompt.txt     # Prompt template
// │       └── config.json      # Execution settings
// ├── .env
// └── requirements.txt
export function buildSemanticKernelZip(
  ctx: WorkflowExportContext,
  code: string,
): ZipProjectTemplate {
  const name = sanitize(ctx.title);

  const skPrompt = `You are an AI assistant in the workflow: ${ctx.title || 'My Workflow'}.

Input: {{$input}}

Execute your assigned task and return a structured response.`;

  const pluginConfig = JSON.stringify(
    {
      schema: 1,
      description: `Plugin for ${ctx.title || 'workflow'} automation`,
      execution_settings: {
        default: {
          max_tokens: 1024,
          temperature: 0.2,
        },
      },
      input_variables: [{ name: 'input', description: 'The input context', required: true }],
    },
    null,
    2,
  );

  return {
    rootFolder: name,
    files: {
      'main.py': code,
      'plugins/WorkflowPlugin/skprompt.txt': skPrompt,
      'plugins/WorkflowPlugin/config.json': pluginConfig,
      '.env':
        'GLOBAL_LLM_SERVICE=OpenAI\nOPENAI_API_KEY=sk-your-openai-api-key-here\nOPENAI_CHAT_MODEL_ID=gpt-4o-mini\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'requirements.txt': 'semantic-kernel>=1.0.0\npython-dotenv>=1.0.0\n',
      'README.md': [
        `# ${ctx.title || 'My Semantic Kernel App'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **Semantic Kernel (Microsoft)**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv && source .venv/bin/activate',
        'pip install -r requirements.txt',
        '# Configure .env with your API keys',
        'python main.py',
        '```',
        '',
        '## Plugin Structure',
        '',
        '```',
        'plugins/WorkflowPlugin/',
        '    skprompt.txt   # The AI prompt template',
        '    config.json    # Temperature, max_tokens, input variables',
        '```',
      ].join('\n'),
    },
  };
}

// ─── 10. Custom Agent Framework ──────────────────────────────────────────────
// Structure: Pure Python, src/ layout, engine/ module
// my_custom_agent/
// ├── src/
// │   └── main.py
// ├── engine/
// │   ├── __init__.py
// │   └── workflow.py
// ├── .env
// ├── .gitignore
// └── requirements.txt
export function buildCustomAgentZip(ctx: WorkflowExportContext, code: string): ZipProjectTemplate {
  const name = sanitize(ctx.title);

  const enginePy =
    [
      '"""Custom Workflow Engine – Core Orchestration Module"""',
      'import time',
      'from dataclasses import dataclass, field',
      'from typing import Callable, Dict, Any, List',
      '',
      '@dataclass',
      'class WorkflowState:',
      '    data: Dict[str, Any] = field(default_factory=dict)',
      '    logs: List[str] = field(default_factory=list)',
      '',
      '@dataclass',
      'class WorkflowNode:',
      '    id: str',
      '    name: str',
      '    action: Callable[["WorkflowState"], Dict[str, Any]]',
      '    retries: int = 2',
      '',
      'class CustomWorkflowEngine:',
      '    def __init__(self):',
      '        self.nodes: List[WorkflowNode] = []',
      '        self.state = WorkflowState()',
      '',
      '    def add_step(self, node: WorkflowNode):',
      '        self.nodes.append(node)',
      '',
      '    def run(self, initial_data: Dict[str, Any] = None) -> WorkflowState:',
      '        if initial_data:',
      '            self.state.data.update(initial_data)',
      '        print("=== EXECUTING CUSTOM AGENT ENGINE ===")',
      '        for node in self.nodes:',
      '            attempts, success = 0, False',
      '            while attempts <= node.retries and not success:',
      '                try:',
      '                    start = time.time()',
      '                    print(f"Executing: [{node.name}] (attempt {attempts + 1})...")',
      '                    output = node.action(self.state)',
      '                    self.state.data.update(output)',
      '                    ms = round((time.time() - start) * 1000, 2)',
      '                    self.state.logs.append(f"✓ {node.name} completed in {ms}ms")',
      '                    success = True',
      '                except Exception as e:',
      '                    attempts += 1',
      '                    print(f"  Error in {node.name}: {e}")',
      '                    if attempts > node.retries:',
      '                        self.state.logs.append(f"✗ {node.name} failed: {e}")',
      '                        raise',
      '        print("=== WORKFLOW FINISHED ===")',
      '        return self.state',
    ].join('\n') + '\n';

  return {
    rootFolder: name,
    files: {
      'src/main.py': code,
      'engine/__init__.py':
        'from .workflow import CustomWorkflowEngine, WorkflowState, WorkflowNode\n\n__all__ = ["CustomWorkflowEngine", "WorkflowState", "WorkflowNode"]\n',
      'engine/workflow.py': enginePy,
      '.env': '# Add any API keys your workflow steps use\n# OPENAI_API_KEY=your_key_here\n',
      '.gitignore': '.env\n__pycache__/\n*.pyc\nvenv/\n.venv/\n',
      'requirements.txt':
        '# No external agent frameworks required – pure Python stdlib\npython-dotenv>=1.0.0\n',
      'README.md': [
        `# ${ctx.title || 'My Custom Agent'}`,
        '',
        '> Generated by **AutoAgent** · Framework: **Custom Agent Framework**',
        '',
        '## Quick Start',
        '',
        '```bash',
        'python -m venv .venv && source .venv/bin/activate',
        'pip install -r requirements.txt',
        'python src/main.py',
        '```',
      ].join('\n'),
    },
  };
}

type BuilderFn = (ctx: WorkflowExportContext, code: string) => ZipProjectTemplate;

export const ZIP_BUILDERS: Record<string, BuilderFn> = {
  raw_llm: buildRawLLMZip,
  google_adk: buildGoogleADKZip,
  langchain: buildLangChainZip,
  langgraph: buildLangGraphZip,
  openai_agents: buildOpenAIAgentsZip,
  crewai: buildCrewAIZip,
  autogen: buildAutoGenZip,
  llamaindex: buildLlamaIndexZip,
  semantic_kernel: buildSemanticKernelZip,
  custom_agent: buildCustomAgentZip,
};

export async function downloadFrameworkZip(
  approachId: string,
  ctx: WorkflowExportContext,
  code: string,
  zipFilename: string,
): Promise<void> {
  const builder = ZIP_BUILDERS[approachId] ?? buildRawLLMZip;
  const template = builder(ctx, code);

  const zip = new JSZip();
  const root = zip.folder(template.rootFolder)!;

  for (const [filePath, content] of Object.entries(template.files)) {
    const parts = filePath.split('/');
    let folder = root;
    for (let i = 0; i < parts.length - 1; i++) {
      folder = folder.folder(parts[i])!;
    }
    folder.file(parts[parts.length - 1], content);
  }

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = zipFilename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
